.TH "NOEUD" 3 "Wed Feb 8 2017" "Version 0.1" "SHELL_HEIL_BOUROUIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NOEUD \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP \fBval\fP"
.br
.ti -1c
.RI "struct \fBNOEUD\fP * \fBfg\fP"
.br
.ti -1c
.RI "struct \fBNOEUD\fP * \fBfd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SHELL_HEIL_BOUROUIS from the source code\&.
